# Generated by Django 5.2.8 on 2025-11-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgffile',
            name='casanovo_file_name',
            field=models.CharField(default='casanovo_20251029091517', max_length=255),
        ),
    ]
