# Generated by Django 5.2.8 on 2025-11-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mgffile_casanovo_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgffile',
            name='casanovo_file_name',
            field=models.CharField(max_length=255),
        ),
    ]
