# Generated by Django 5.2.8 on 2025-11-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='sequence',
            field=models.TextField(default=''),
        ),
    ]
