# Generated by Django 5.2.8 on 2025-11-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mfgfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MfgFile',
            new_name='MgfFile',
        ),
    ]
