from pyteomics import mgf


# (1) Read MS/MS spectra from an MGF file.

# See: https://pyteomics.readthedocs.io/en/latest/api/mgf.html

mgf_file_path = "../../resources/sample_preprocessed_spectra.mgf"

with mgf.read(mgf_file_path) as reader:
    for i, spec in enumerate(reader, start=1):
        mz = spec["m/z array"]  # numpy array of fragment m/z
        inten = spec["intensity array"]  # numpy array of fragment intensities
        meta = spec["params"]  # dict of spectrum-level metadata

        title = meta.get("title")
        pepmass = meta.get("pepmass")  # (precursor_mz, intensity?) or float
        charge = meta.get("charge")
        rt = meta.get("rtinseconds")

        print(mz)


# (2) Read PSMs from an mzTab file generated by our Casanovo de novo peptide sequencing tool.