import re

import pandas as pd
from pyteomics import mgf
import matplotlib.pyplot as plt
import spectrum_utils.plot as sup
import spectrum_utils.spectrum as sus


def read_mgf_file(path):
    spectra = []
    with mgf.read(path) as reader:
        for spec in reader:
            title = spec["params"].get("title", "")
            scan_match = re.search(r"scan=(\d+)", title)
            scan = int(scan_match.group(1)) if scan_match else None

            # Precursor info
            pepmass = spec["params"].get("pepmass")
            precursor_mz = pepmass[0] if isinstance(pepmass, (list, tuple)) else pepmass
            charge = spec["params"].get("charge", [None])
            precursor_charge = charge[0] if isinstance(charge, (list, tuple)) else charge

            su_spec = sus.MsmsSpectrum(
                identifier=title,
                precursor_mz=precursor_mz,
                precursor_charge=precursor_charge,
                mz=spec["m/z array"],
                intensity=spec["intensity array"],
            )

            spectra.append({"scan": scan, "spectrum": su_spec})
    return spectra

def read_mztab_file(mztab_path):
    # Load the mzTab file
    # psm_df = pd.read_csv(
    #     mztab_path,
    #     sep="\t",
    #     engine="python",
    # )

    psm_df = pd.read_csv(mztab_path, sep='\t', skiprows=65)

    return psm_df


# -- Read PSMs from an mzTab file generated by our Casanovo de novo peptide sequencing tool.
mztab_path = "../../resources/casanovo_20251029091517.mztab"
psm_df = read_mztab_file(mztab_path)


mgf_file_path = "../../resources/sample_preprocessed_spectra.mgf"
# spectra = read_mgf_file(mgf_file_path)
# spectra_df = pd.DataFrame(spectra)

# try merging:

spectra = []
with mgf.read(mgf_file_path) as reader:
    for spec in reader:

        # psm_df['sequence']
        # spec['seq']
        a = spec['params']['seq']
        b = psm_df['sequence'][0]

        if a == b:
            c = 0

        matched_rows = psm_df[psm_df['sequence'] == spec['params']['seq']]

        # title = spec["params"].get("title", "")
        # scan_match = re.search(r"scan=(\d+)", title)
        # scan = int(scan_match.group(1)) if scan_match else None
        #
        # # Precursor info
        # pepmass = spec["params"].get("pepmass")
        # precursor_mz = pepmass[0] if isinstance(pepmass, (list, tuple)) else pepmass
        # charge = spec["params"].get("charge", [None])
        # precursor_charge = charge[0] if isinstance(charge, (list, tuple)) else charge
        #
        # su_spec = sus.MsmsSpectrum(
        #     identifier=title,
        #     precursor_mz=precursor_mz,
        #     precursor_charge=precursor_charge,
        #     mz=spec["m/z array"],
        #     intensity=spec["intensity array"],
        # )
        #
        # spectra.append({"scan": scan, "spectrum": su_spec})



merged = pd.merge(psm_df, spectra_df, on="scan", how="inner")
print(f"Matched {len(merged)} spectra to PSMs")




# # --- Load mzTab PSMs ---
# mztab_path = "../../resources/casanovo_20251029091517.mztab"
# # Parse mzTab manually since Casanovo or spectrum_utils doesn't do that part directly
# psm_df = pd.read_csv(
#     mztab_path,
#     sep="\t",
#     comment="#",
#     header=None,
#     names=[f"col{i}" for i in range(20)]  # you can adjust
# )
# # Filter to PSM rows only
# psm_df = psm_df[psm_df[0].str.startswith("PSM")]
#
# # Extract scan number or spectrum reference
# psm_df["scan"] = psm_df[10].str.extract(r"scan=(\d+)").astype(float)  # adjust column index as needed


# # -- Read MS/MS spectra from an MGF file.
#
# # See: https://pyteomics.readthedocs.io/en/latest/api/mgf.html
#
# mgf_file_path = "../../resources/sample_preprocessed_spectra.mgf"
#
# spectra = []
#
# with mgf.read(mgf_file_path) as reader:
#     for i, spec in enumerate(reader, start=1):
#         mz = spec["m/z array"]  # numpy array of fragment m/z
#         inten = spec["intensity array"]  # numpy array of fragment intensities
#         meta = spec["params"]  # dict of spectrum-level metadata
#
#         title = meta.get("title")
#         pepmass = meta.get("pepmass")  # (precursor_mz, intensity?) or float
#         charge = meta.get("charge")
#         rt = meta.get("rtinseconds")
#
#         # print(mz)
#
#         # TODO change: source: from ChatGPT
#         title = spec["params"].get("title", "")
#         scan_match = re.search(r"scan=(\d+)", title)
#         scan = int(scan_match.group(1)) if scan_match else None
#         su_spec = sus.MsmsSpectrum(
#             identifier=title,
#             precursor_mz=spec["params"]["pepmass"][0],
#             precursor_charge=spec["params"].get("charge", [None])[0],
#             mz=spec["m/z array"],
#             intensity=spec["intensity array"],
#         )
#         spectra.append({"scan": scan, "spectrum": su_spec})
#
#     # TODO change: source: from ChatGPT
#
#     spectra_df = pd.DataFrame(spectra)
#
#     # # --- Match spectra to PSMs by scan number ---
#     # merged = pd.merge(psm_df, spectra_df, on="scan", how="inner")
#     #
#     # print(f"Matched {len(merged)} spectra to PSMs")
#     #
#     # # Example: visualize one match
#     # example_spec = merged.iloc[0]["spectrum"]
#     # print(f"Spectrum ID: {example_spec.identifier}, precursor m/z: {example_spec.precursor_mz}")
#
# # (2) Read PSMs from an mzTab file generated by our Casanovo de novo peptide sequencing tool.
#